// frontend/app/src/pages/admin/flows/flowData.ts
import type { Node, Edge } from '@xyflow/react';
import { VEHICLE_STATE_LABEL, VEHICLE_STATE_TONE } from '../../../lib/labels';
import { SERVICE_QUEUE_LABEL, SOURCE_LABEL, LIABILITY_LABEL } from '../../../lib/serviceJobLabels';
import type { UserRole } from '../../../types';
import type { FlowNodeData, FlowEdgeData, FlowMode } from './types';

// ---------- helpers ----------
const ALL_ROLES: UserRole[] = ['SUPER_ADMIN', 'TENANT_ADMIN', 'FLEET_STAFF', 'SERVICE_MANAGER'];
const allCan = { canView: true, canAct: true };
const viewOnly = { canView: true, canAct: false };
const rbac = (act: UserRole[]): Record<UserRole, { canView: boolean; canAct: boolean }> =>
  Object.fromEntries(ALL_ROLES.map((r) => [r, act.includes(r) ? allCan : viewOnly])) as Record<
    UserRole,
    { canView: boolean; canAct: boolean }
  >;

// ---------- Vehicle state nodes ----------
export const VEHICLE_NODES: Node<FlowNodeData>[] = [
  {
    id: 'INDUCTED',
    position: { x: 0, y: 0 },
    type: 'flow',
    data: {
      label: VEHICLE_STATE_LABEL.INDUCTED,
      description: 'Just added to the system, not yet checked',
      tone: VEHICLE_STATE_TONE.INDUCTED,
      screens: [{ path: '/vehicles/new', label: 'Add vehicle' }],
      actors: ['SUPER_ADMIN', 'TENANT_ADMIN', 'FLEET_STAFF'],
      actions: ['Add vehicle to registry'],
      triggers: ['Vehicle purchased or transferred in'],
      typeName: 'VehicleState',
      relatedTypes: ['Vehicle', 'VehicleDetail'],
      fields: [
        { name: 'id', type: 'string', example: 'EV-0042' },
        { name: 'chassisNumber', type: 'string', example: 'MBLA08AZ7N5012345' },
        { name: 'model', type: 'string', example: 'e-Sprinto' },
        { name: 'state', type: 'VehicleState', example: 'INDUCTED' },
      ],
      permissions: rbac(['SUPER_ADMIN', 'TENANT_ADMIN', 'FLEET_STAFF']),
      permissionFn: 'canEditVehicle',
      asIs: 'problematic',
      toBe: 'modified',
      changeNote: 'Now routes to QC_PENDING instead of READY_TO_DEPLOY',
      problems: ['P4'],
    },
  },
  {
    id: 'QC_PENDING',
    position: { x: 400, y: 0 },
    type: 'flow',
    data: {
      label: SERVICE_QUEUE_LABEL.QC_PENDING,
      description: 'Waiting for quality check before release',
      tone: VEHICLE_STATE_TONE.QC_PENDING,
      screens: [{ path: '/service/qc', label: 'QC queue' }],
      actors: ALL_ROLES,
      actions: ['Inspect bike', 'Pass QC', 'Fail QC'],
      triggers: ['Work completed', 'Induction check', 'Deboard with no damage'],
      typeName: 'VehicleState',
      relatedTypes: ['ServiceJob', 'InspectionRequest'],
      fields: [
        { name: 'queue', type: 'ServiceQueue', example: 'QC_PENDING' },
        { name: 'status', type: 'ServiceJobStatus', example: 'OPEN' },
      ],
      permissions: rbac(ALL_ROLES),
      permissionFn: 'canManageService',
      asIs: 'exists',
      toBe: 'modified',
      changeNote: 'Now the SOLE gate back to fleet — no bypass paths',
      problems: [],
    },
  },
  {
    id: 'READY_TO_DEPLOY',
    position: { x: 800, y: 0 },
    type: 'flow',
    data: {
      label: VEHICLE_STATE_LABEL.READY_TO_DEPLOY,
      description: 'Checked, free, can go out to a rider',
      tone: VEHICLE_STATE_TONE.READY_TO_DEPLOY,
      screens: [{ path: '/vehicles?state=READY_TO_DEPLOY', label: 'Vehicles (filtered)' }],
      actors: ['SUPER_ADMIN', 'TENANT_ADMIN', 'FLEET_STAFF'],
      actions: ['Assign to rider', 'Retire'],
      triggers: ['QC passed'],
      typeName: 'VehicleState',
      relatedTypes: ['Vehicle'],
      fields: [
        { name: 'state', type: 'VehicleState', example: 'READY_TO_DEPLOY' },
        { name: 'currentRiderId', type: 'null', example: 'null' },
      ],
      permissions: rbac(['SUPER_ADMIN', 'TENANT_ADMIN', 'FLEET_STAFF']),
      permissionFn: null,
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
      problems: [],
    },
  },
  {
    id: 'DEPLOYED',
    position: { x: 1200, y: 0 },
    type: 'flow',
    data: {
      label: VEHICLE_STATE_LABEL.DEPLOYED,
      description: 'Out on the road with an active rider',
      tone: VEHICLE_STATE_TONE.DEPLOYED,
      screens: [{ path: '/vehicles?state=DEPLOYED', label: 'Vehicles (filtered)' }],
      actors: ['SUPER_ADMIN', 'TENANT_ADMIN', 'FLEET_STAFF'],
      actions: ['Deboard rider', 'Exchange vehicle', 'Log RSA/QRT'],
      triggers: ['Assigned to rider'],
      typeName: 'VehicleState',
      relatedTypes: ['Vehicle', 'Rider'],
      fields: [
        { name: 'state', type: 'VehicleState', example: 'DEPLOYED' },
        { name: 'currentRiderId', type: 'string', example: 'RDR-0012' },
        { name: 'currentRiderName', type: 'string', example: 'Arun K' },
      ],
      permissions: rbac(['SUPER_ADMIN', 'TENANT_ADMIN', 'FLEET_STAFF']),
      permissionFn: null,
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
      problems: ['P5'],
    },
  },
  {
    id: 'UNDER_REPAIR',
    position: { x: 800, y: 400 },
    type: 'flow',
    data: {
      label: VEHICLE_STATE_LABEL.UNDER_REPAIR,
      description: 'At the hub, being worked on (any service queue)',
      tone: VEHICLE_STATE_TONE.UNDER_REPAIR,
      screens: [
        { path: '/service/queues', label: 'Bikes in service' },
        { path: '/service/assistance', label: 'Help desk' },
      ],
      actors: ALL_ROLES,
      actions: ['Assess damage', 'Repair', 'Move queue', 'Send to QC'],
      triggers: ['Deboard with damage', 'Walk-in', 'RSA/QRT pickup arrived', 'QC failed'],
      typeName: 'VehicleState',
      relatedTypes: ['ServiceJob', 'ServiceQueue'],
      fields: [
        { name: 'queue', type: 'ServiceQueue', example: 'MINOR_REPAIR' },
        { name: 'items', type: 'ServiceJobItem[]', example: '[{label:"Headlamp", costPaise:96000}]' },
        { name: 'technician', type: 'string | null', example: 'Abhinandan' },
      ],
      permissions: rbac(ALL_ROLES),
      permissionFn: 'canManageService',
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
      problems: ['P6'],
    },
  },
  {
    id: 'RECOVERY',
    position: { x: 1200, y: 400 },
    type: 'flow',
    data: {
      label: VEHICLE_STATE_LABEL.RECOVERY,
      description: 'Bike in the field, team dispatched to collect it',
      tone: VEHICLE_STATE_TONE.RECOVERY,
      screens: [
        { path: '/recovery', label: 'Recovery board' },
        { path: '/vehicles?state=RECOVERY', label: 'Vehicles (filtered)' },
      ],
      actors: ['SUPER_ADMIN', 'TENANT_ADMIN', 'FLEET_STAFF'],
      actions: ['Track pickup', 'Mark arrived at hub'],
      triggers: ['RSA call', 'QRT dispatch'],
      typeName: 'VehicleState',
      relatedTypes: ['Vehicle', 'RecoveryCounts'],
      fields: [
        { name: 'state', type: 'VehicleState', example: 'RECOVERY' },
        { name: 'source', type: 'ServiceJobSource', example: 'RSA' },
      ],
      permissions: rbac(['SUPER_ADMIN', 'TENANT_ADMIN', 'FLEET_STAFF']),
      permissionFn: null,
      asIs: 'dead',
      toBe: 'modified',
      changeNote:
        'Now a real operational state — RSA/QRT creates it. No more direct-to-UNDER_REPAIR.',
      problems: ['P2'],
    },
  },
  {
    id: 'ACCIDENT',
    position: { x: 400, y: 400 },
    type: 'flow',
    data: {
      label: VEHICLE_STATE_LABEL.ACCIDENT,
      description: 'Serious incident — investigation or major repair',
      tone: VEHICLE_STATE_TONE.ACCIDENT,
      screens: [{ path: '/vehicles?state=ACCIDENT', label: 'Vehicles (filtered)' }],
      actors: ALL_ROLES,
      actions: ['Investigate', 'Start repair', 'Retire'],
      triggers: ['Accident reported at deboard/exchange/RSA'],
      typeName: 'VehicleState',
      relatedTypes: ['ServiceJob'],
      fields: [
        { name: 'queue', type: 'ServiceQueue', example: 'ACCIDENT' },
        { name: 'damageCategory', type: 'DamageCategory', example: 'ACCIDENT' },
      ],
      permissions: rbac(ALL_ROLES),
      permissionFn: 'canManageService',
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
      problems: ['P7'],
    },
  },
  {
    id: 'RETURNED',
    position: { x: 1200, y: 200 },
    type: 'flow',
    data: {
      label: VEHICLE_STATE_LABEL.RETURNED,
      description: 'DEAD STATE — no operation in the code creates this',
      tone: VEHICLE_STATE_TONE.RETURNED,
      screens: [],
      actors: [],
      actions: [],
      triggers: [],
      typeName: 'VehicleState',
      relatedTypes: [],
      fields: [],
      permissions: rbac([]),
      permissionFn: null,
      asIs: 'dead',
      toBe: 'removed',
      changeNote:
        'Removed — no operation ever creates this state. Bikes go directly to their target state at deboard.',
      problems: ['P1'],
    },
  },
  {
    id: 'RETIRED',
    position: { x: 0, y: 400 },
    type: 'flow',
    data: {
      label: VEHICLE_STATE_LABEL.RETIRED,
      description: 'End of life, out of the fleet permanently',
      tone: VEHICLE_STATE_TONE.RETIRED,
      screens: [{ path: '/vehicles?state=RETIRED', label: 'Vehicles (filtered)' }],
      actors: ['SUPER_ADMIN', 'TENANT_ADMIN'],
      actions: [],
      triggers: ['Scrapped — beyond repair or end of service life'],
      typeName: 'VehicleState',
      relatedTypes: ['Vehicle'],
      fields: [{ name: 'state', type: 'VehicleState', example: 'RETIRED' }],
      permissions: rbac(['SUPER_ADMIN', 'TENANT_ADMIN']),
      permissionFn: 'canEditVehicle',
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
      problems: [],
    },
  },
];

// ---------- Vehicle state edges ----------
export const VEHICLE_EDGES: Edge<FlowEdgeData>[] = [
  // Happy path
  {
    id: 'e-inducted-qc',
    source: 'INDUCTED',
    target: 'QC_PENDING',
    type: 'flow',
    data: {
      trigger: 'Induction check',
      actor: ['FLEET_STAFF'],
      operation: 'addVehicle()',
      modes: ['operational', 'data', 'rbac', 'asis'],
      asIs: 'exists',
      toBe: 'added',
      changeNote: 'NEW: was INDUCTED→RTD, now mandatory QC',
    },
  },
  {
    id: 'e-inducted-rtd',
    source: 'INDUCTED',
    target: 'READY_TO_DEPLOY',
    type: 'flow',
    data: {
      trigger: 'Skip QC (as-is only)',
      actor: ['FLEET_STAFF'],
      operation: 'addVehicle()',
      modes: ['operational', 'asis'],
      asIs: 'exists',
      toBe: 'removed',
      changeNote: 'REMOVED: no more skipping induction QC',
    },
  },
  {
    id: 'e-qc-rtd',
    source: 'QC_PENDING',
    target: 'READY_TO_DEPLOY',
    type: 'flow',
    data: {
      trigger: 'QC passed',
      actor: ALL_ROLES,
      operation: 'updateServiceJob()',
      modes: ['operational', 'data', 'rbac', 'asis'],
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
    },
  },
  {
    id: 'e-rtd-deployed',
    source: 'READY_TO_DEPLOY',
    target: 'DEPLOYED',
    type: 'flow',
    data: {
      trigger: 'Assigned to rider',
      actor: ['FLEET_STAFF'],
      operation: 'assignVehicle()',
      modes: ['operational', 'data', 'rbac', 'asis'],
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
    },
  },

  // Return paths
  {
    id: 'e-deployed-repair',
    source: 'DEPLOYED',
    target: 'UNDER_REPAIR',
    type: 'flow',
    data: {
      trigger: 'Deboard/walk-in with damage',
      actor: ['FLEET_STAFF'],
      operation: 'deboardRider() / createServiceJob()',
      modes: ['operational', 'data', 'rbac', 'asis'],
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
    },
  },
  {
    id: 'e-deployed-recovery',
    source: 'DEPLOYED',
    target: 'RECOVERY',
    type: 'flow',
    data: {
      trigger: SOURCE_LABEL.RSA + ' / ' + SOURCE_LABEL.QRT,
      actor: ['FLEET_STAFF'],
      operation: 'createServiceJob()',
      modes: ['operational', 'data', 'rbac', 'asis'],
      asIs: 'exists',
      toBe: 'modified',
      changeNote:
        'Now the first step for RSA/QRT — bike was going directly to UNDER_REPAIR',
    },
  },
  {
    id: 'e-deployed-accident',
    source: 'DEPLOYED',
    target: 'ACCIDENT',
    type: 'flow',
    data: {
      trigger: 'Accident reported',
      actor: ['FLEET_STAFF'],
      operation: 'deboardRider() / createServiceJob()',
      modes: ['operational', 'data', 'rbac', 'asis'],
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
    },
  },
  {
    id: 'e-deployed-qc',
    source: 'DEPLOYED',
    target: 'QC_PENDING',
    type: 'flow',
    data: {
      trigger: 'Deboard with no damage',
      actor: ['FLEET_STAFF'],
      operation: 'deboardRider()',
      modes: ['operational', 'data', 'rbac', 'asis'],
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
    },
  },

  // Recovery → hub
  {
    id: 'e-recovery-repair',
    source: 'RECOVERY',
    target: 'UNDER_REPAIR',
    type: 'flow',
    data: {
      trigger: 'Bike brought to hub',
      actor: ['FLEET_STAFF'],
      operation: 'updateServiceJob()',
      modes: ['operational', 'data', 'rbac', 'asis'],
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
    },
  },
  {
    id: 'e-recovery-accident',
    source: 'RECOVERY',
    target: 'ACCIDENT',
    type: 'flow',
    data: {
      trigger: 'Found accident damage on pickup',
      actor: ['FLEET_STAFF'],
      operation: 'updateServiceJob()',
      modes: ['operational', 'asis'],
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
    },
  },

  // Service loop
  {
    id: 'e-repair-qc',
    source: 'UNDER_REPAIR',
    target: 'QC_PENDING',
    type: 'flow',
    data: {
      trigger: 'Work done, sent for QC',
      actor: ALL_ROLES,
      operation: 'updateServiceJob()',
      modes: ['operational', 'data', 'rbac', 'asis'],
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
    },
  },
  {
    id: 'e-qc-fail',
    source: 'QC_PENDING',
    target: 'UNDER_REPAIR',
    type: 'flow',
    data: {
      trigger: 'QC failed',
      actor: ALL_ROLES,
      operation: 'updateServiceJob()',
      modes: ['operational', 'data', 'rbac', 'asis'],
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
    },
  },
  {
    id: 'e-accident-repair',
    source: 'ACCIDENT',
    target: 'UNDER_REPAIR',
    type: 'flow',
    data: {
      trigger: 'Investigation done, start repair',
      actor: ALL_ROLES,
      operation: 'updateServiceJob()',
      modes: ['operational', 'asis'],
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
    },
  },
  {
    id: 'e-repair-accident',
    source: 'UNDER_REPAIR',
    target: 'ACCIDENT',
    type: 'flow',
    data: {
      trigger: 'Escalated to accident',
      actor: ALL_ROLES,
      operation: 'updateServiceJob()',
      modes: ['operational', 'asis'],
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
    },
  },

  // Retirement
  {
    id: 'e-rtd-retired',
    source: 'READY_TO_DEPLOY',
    target: 'RETIRED',
    type: 'flow',
    data: {
      trigger: 'Scrapped',
      actor: ['SUPER_ADMIN', 'TENANT_ADMIN'],
      operation: 'retireVehicle()',
      modes: ['operational', 'asis'],
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
    },
  },
  {
    id: 'e-repair-retired',
    source: 'UNDER_REPAIR',
    target: 'RETIRED',
    type: 'flow',
    data: {
      trigger: 'Beyond repair',
      actor: ['SUPER_ADMIN', 'TENANT_ADMIN'],
      operation: 'retireVehicle()',
      modes: ['operational', 'asis'],
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
    },
  },
  {
    id: 'e-recovery-retired',
    source: 'RECOVERY',
    target: 'RETIRED',
    type: 'flow',
    data: {
      trigger: 'Unrecoverable',
      actor: ['SUPER_ADMIN', 'TENANT_ADMIN'],
      operation: 'retireVehicle()',
      modes: ['operational', 'asis'],
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
    },
  },
  {
    id: 'e-accident-retired',
    source: 'ACCIDENT',
    target: 'RETIRED',
    type: 'flow',
    data: {
      trigger: 'Total loss',
      actor: ['SUPER_ADMIN', 'TENANT_ADMIN'],
      operation: 'retireVehicle()',
      modes: ['operational', 'asis'],
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
    },
  },

  // As-is bypass paths (removed in to-be)
  {
    id: 'e-deployed-rtd-bypass',
    source: 'DEPLOYED',
    target: 'READY_TO_DEPLOY',
    type: 'flow',
    data: {
      trigger: 'Deboard override (as-is only)',
      actor: ['FLEET_STAFF'],
      operation: 'deboardRider()',
      modes: ['asis'],
      asIs: 'bypass',
      toBe: 'removed',
      changeNote: 'REMOVED: no more skipping QC at deboard',
    },
  },
  {
    id: 'e-recovery-rtd-bypass',
    source: 'RECOVERY',
    target: 'READY_TO_DEPLOY',
    type: 'flow',
    data: {
      trigger: 'Direct to fleet (as-is only)',
      actor: ['FLEET_STAFF'],
      operation: '-',
      modes: ['asis'],
      asIs: 'bypass',
      toBe: 'removed',
      changeNote: 'REMOVED: must go through UNDER_REPAIR → QC',
    },
  },
  {
    id: 'e-repair-rtd-bypass',
    source: 'UNDER_REPAIR',
    target: 'READY_TO_DEPLOY',
    type: 'flow',
    data: {
      trigger: 'Skip QC intent (as-is only)',
      actor: ALL_ROLES,
      operation: 'updateServiceJob()',
      modes: ['asis'],
      asIs: 'bypass',
      toBe: 'removed',
      changeNote: 'REMOVED: QC is now mandatory',
    },
  },
];

// ---------- Money flow nodes ----------
export const MONEY_NODES: Node<FlowNodeData>[] = [
  {
    id: 'M_JOB_OPEN',
    position: { x: 0, y: 0 },
    type: 'flow',
    data: {
      label: 'Service job opens',
      description: 'Work begins — nothing charged yet',
      tone: 'neutral',
      screens: [{ path: '/service/assistance', label: 'Help desk' }],
      actors: ALL_ROLES,
      actions: ['Record parts', 'Record labour'],
      triggers: ['Bike taken in for service'],
      typeName: 'ServiceJob',
      fields: [{ name: 'totalCostPaise', type: 'number', example: '0' }],
      relatedTypes: ['ServiceJobItem'],
      permissions: rbac(ALL_ROLES),
      permissionFn: 'canManageService',
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
      problems: [],
      moneyDetail: 'No charge while the job is open. Parts and labour are recorded but not billed.',
    },
  },
  {
    id: 'M_JOB_CLOSE',
    position: { x: 400, y: 0 },
    type: 'flow',
    data: {
      label: 'Job closes',
      description: 'Bike goes back out, cost finalised',
      tone: 'caution',
      screens: [{ path: '/service/assistance', label: 'Help desk' }],
      actors: ['SUPER_ADMIN', 'TENANT_ADMIN', 'FLEET_STAFF'],
      actions: ['Decide liability'],
      triggers: ['QC passed, bike released'],
      typeName: 'ServiceJob',
      fields: [
        { name: 'totalCostPaise', type: 'number', example: '180000' },
        { name: 'liability', type: 'ServiceLiability', example: 'RIDER' },
      ],
      relatedTypes: ['ServiceLiability'],
      permissions: rbac(['SUPER_ADMIN', 'TENANT_ADMIN', 'FLEET_STAFF']),
      permissionFn: 'canCloseServiceJob',
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
      problems: [],
      moneyDetail:
        'Liability decided: ' +
        LIABILITY_LABEL.DEPOSIT +
        ', ' +
        LIABILITY_LABEL.RIDER +
        ', or ' +
        LIABILITY_LABEL.COMPANY +
        '.',
    },
  },
  {
    id: 'M_DEPOSIT',
    position: { x: 200, y: 200 },
    type: 'flow',
    data: {
      label: LIABILITY_LABEL.DEPOSIT,
      description: 'Deducted from rider deposit held on file',
      tone: 'warn',
      screens: [],
      actors: ['SUPER_ADMIN', 'TENANT_ADMIN', 'FLEET_STAFF'],
      actions: ['Deduct from deposit'],
      triggers: ['Liability = deposit'],
      typeName: 'Rider',
      fields: [{ name: 'depositHeld', type: 'Paise', example: '500000' }],
      relatedTypes: ['ServiceJob'],
      permissions: rbac(['SUPER_ADMIN', 'TENANT_ADMIN', 'FLEET_STAFF']),
      permissionFn: 'canCloseServiceJob',
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
      problems: [],
      moneyDetail: 'Deposit goes down immediately. Rider is refunded what remains at deboard.',
    },
  },
  {
    id: 'M_RIDER_PAYS',
    position: { x: 600, y: 200 },
    type: 'flow',
    data: {
      label: LIABILITY_LABEL.RIDER,
      description: 'Added to rider weekly bill',
      tone: 'bad',
      screens: [{ path: '/payments/run', label: 'Weekly payment run' }],
      actors: ['SUPER_ADMIN', 'TENANT_ADMIN'],
      actions: ['Collect payment'],
      triggers: ['Liability = rider'],
      typeName: 'RiderCharge',
      fields: [{ name: 'amount', type: 'Paise', example: '96000' }],
      relatedTypes: ['PaymentRun'],
      permissions: rbac(['SUPER_ADMIN', 'TENANT_ADMIN']),
      permissionFn: 'canCollectPayments',
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
      problems: [],
      moneyDetail: 'Charge appears in the next weekly payment run as a repair line item.',
    },
  },
  {
    id: 'M_COMPANY',
    position: { x: 400, y: 200 },
    type: 'flow',
    data: {
      label: LIABILITY_LABEL.COMPANY,
      description: 'Nothing charged to the rider',
      tone: 'good',
      screens: [],
      actors: ['SUPER_ADMIN', 'TENANT_ADMIN', 'FLEET_STAFF'],
      actions: [],
      triggers: ['Liability = company'],
      typeName: 'ServiceJob',
      fields: [],
      relatedTypes: [],
      permissions: rbac(['SUPER_ADMIN', 'TENANT_ADMIN', 'FLEET_STAFF']),
      permissionFn: 'canCloseServiceJob',
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
      problems: [],
      moneyDetail: 'Company absorbs the cost. No charge to rider, no deposit deduction.',
    },
  },
  {
    id: 'M_PAYMENT_RUN',
    position: { x: 600, y: 400 },
    type: 'flow',
    data: {
      label: 'Weekly payment run',
      description: 'Rent + repair charges collected',
      tone: 'accent',
      screens: [{ path: '/payments/run', label: 'Weekly payment run' }],
      actors: ['SUPER_ADMIN', 'TENANT_ADMIN'],
      actions: ['Record payment', 'Mark partial'],
      triggers: ['Wednesday billing cycle'],
      typeName: 'PaymentRun',
      fields: [{ name: 'totalDue', type: 'Paise', example: '279900' }],
      relatedTypes: ['RiderCharge'],
      permissions: rbac(['SUPER_ADMIN', 'TENANT_ADMIN']),
      permissionFn: 'canCollectPayments',
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
      problems: [],
      moneyDetail: 'Weekly cycle. Rent + any repair charges. UPI, cash, or bank transfer.',
    },
  },
  {
    id: 'M_OVERDUE',
    position: { x: 600, y: 600 },
    type: 'flow',
    data: {
      label: 'Overdue',
      description: 'Not paid — dunning ladder starts',
      tone: 'bad',
      screens: [{ path: '/payments/overdue', label: 'Overdue riders' }],
      actors: ['SUPER_ADMIN', 'TENANT_ADMIN'],
      actions: ['Send reminder', 'Escalate', 'Repossess'],
      triggers: ['Payment not received by due date'],
      typeName: 'OverdueRider',
      fields: [{ name: 'stage', type: 'DunningStage', example: 'WARNING_1' }],
      relatedTypes: ['DunningStage'],
      permissions: rbac(['SUPER_ADMIN', 'TENANT_ADMIN']),
      permissionFn: 'canCollectPayments',
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
      problems: [],
      moneyDetail: 'Dunning ladder: reminder → warning 1 → warning 2 → take the bike back.',
    },
  },
  {
    id: 'M_RECOVERY',
    position: { x: 600, y: 800 },
    type: 'flow',
    data: {
      label: 'Recovery',
      description: 'Bike repossessed or missing',
      tone: 'warn',
      screens: [{ path: '/recovery', label: 'Recovery board' }],
      actors: ['SUPER_ADMIN', 'TENANT_ADMIN', 'FLEET_STAFF'],
      actions: ['Track', 'Recover', 'Write off'],
      triggers: ['Repossession due', 'Rider unresponsive'],
      typeName: 'RecoveryCounts',
      fields: [],
      relatedTypes: [],
      permissions: rbac(['SUPER_ADMIN', 'TENANT_ADMIN']),
      permissionFn: null,
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
      problems: ['P8'],
      moneyDetail: 'End of the dunning ladder. Team dispatched to collect the bike.',
    },
  },
];

export const MONEY_EDGES: Edge<FlowEdgeData>[] = [
  {
    id: 'me-open-close',
    source: 'M_JOB_OPEN',
    target: 'M_JOB_CLOSE',
    type: 'flow',
    data: {
      trigger: 'QC passed, released',
      actor: ['FLEET_STAFF'],
      operation: 'updateServiceJob()',
      modes: ['money'],
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
    },
  },
  {
    id: 'me-close-deposit',
    source: 'M_JOB_CLOSE',
    target: 'M_DEPOSIT',
    type: 'flow',
    data: {
      trigger: LIABILITY_LABEL.DEPOSIT,
      actor: ['FLEET_STAFF'],
      operation: 'updateServiceJob()',
      modes: ['money'],
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
    },
  },
  {
    id: 'me-close-company',
    source: 'M_JOB_CLOSE',
    target: 'M_COMPANY',
    type: 'flow',
    data: {
      trigger: LIABILITY_LABEL.COMPANY,
      actor: ['FLEET_STAFF'],
      operation: 'updateServiceJob()',
      modes: ['money'],
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
    },
  },
  {
    id: 'me-close-rider',
    source: 'M_JOB_CLOSE',
    target: 'M_RIDER_PAYS',
    type: 'flow',
    data: {
      trigger: LIABILITY_LABEL.RIDER,
      actor: ['FLEET_STAFF'],
      operation: 'updateServiceJob()',
      modes: ['money'],
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
    },
  },
  {
    id: 'me-rider-run',
    source: 'M_RIDER_PAYS',
    target: 'M_PAYMENT_RUN',
    type: 'flow',
    data: {
      trigger: 'Next billing cycle',
      actor: ['TENANT_ADMIN'],
      operation: 'runPayments()',
      modes: ['money'],
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
    },
  },
  {
    id: 'me-run-overdue',
    source: 'M_PAYMENT_RUN',
    target: 'M_OVERDUE',
    type: 'flow',
    data: {
      trigger: 'Not paid',
      actor: ['TENANT_ADMIN'],
      operation: '-',
      modes: ['money'],
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
    },
  },
  {
    id: 'me-overdue-recovery',
    source: 'M_OVERDUE',
    target: 'M_RECOVERY',
    type: 'flow',
    data: {
      trigger: 'Repossession due',
      actor: ['TENANT_ADMIN'],
      operation: '-',
      modes: ['money'],
      asIs: 'exists',
      toBe: 'unchanged',
      changeNote: '',
    },
  },
];

// ---------- Mode selectors ----------

export function nodesForMode(mode: FlowMode): Node<FlowNodeData>[] {
  if (mode === 'money') return MONEY_NODES;
  if (mode === 'asis') return VEHICLE_NODES; // show all including dead/removed
  // operational, data, rbac — hide RETURNED (dead state)
  return VEHICLE_NODES.filter((n) => n.data.asIs !== 'dead');
}

export function edgesForMode(mode: FlowMode, role?: UserRole): Edge<FlowEdgeData>[] {
  if (mode === 'money') return MONEY_EDGES;

  let edges = VEHICLE_EDGES.filter((e) => e.data.modes.includes(mode));

  if (mode === 'asis') return edges; // show all including bypasses

  // operational, data — hide bypass-only edges
  edges = edges.filter((e) => e.data.asIs !== 'bypass');

  // rbac — no further filtering, but the UI will grey out based on role
  return edges;
}
